version: "3"
services:
  object-store-db:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: ${OBJECT_STORE_DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./config/object_store_setup_schema_user_permission.sql:/docker-entrypoint-initdb.d/1-init-schema.sql

  minio:
    image: minio/minio
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data

  object-store-api:
    image: "aafcbicoe/object-store-api:0.2.dev"
    restart: always
    ports:
      - "8081:8080"
    environment:
      spring.datasource.url: ${OBJECT_STORE_SPRING_DATASOURCE_URL}
      spring.datasource.username: ${SPRING_DATASOURCE_USER}
      spring.datasource.password: ${SPRING_DATASOURCE_PASSWORD}
      spring.liquibase.user: ${LIQUIBASE_USER}
      spring.liquibase.password: ${LIQUIBASE_PASSWORD}
      minio.host: minio
      minio.accessKey: ${MINIO_ACCESS_KEY} 
      minio.secretKey: ${MINIO_SECRET_KEY}

  object-store-ui:
    image: aafcbicoe/object-store-ui:0.1.dev
    environment:
      API_ADDRESS: object-store-api:8080
    ports:
      - "2015:8080"

  seqdb-db:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: ${SEQDB_DB_NAME}
      POSTGRES_USER: ${DB_USER_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./config/seqdb_setup_schema_user_permission.sql:/docker-entrypoint-initdb.d/1-init-schema.sql

  seqdb-api:
    image: "aafcbicoe/seqdb-api:1.4.dev"
    restart: always
    ports:
      - "8082:8080"
    environment:
      spring.datasource.url: ${SEQDB_SPRING_DATASOURCE_URL}
      spring.datasource.username: ${SPRING_DATASOURCE_USER}
      spring.datasource.password: ${SPRING_DATASOURCE_PASSWORD}
      spring.liquibase.user: ${LIQUIBASE_USER}
      spring.liquibase.password: ${LIQUIBASE_PASSWORD}
      import-sample-accounts: "true"

  seqdb-ui:
    image: aafcbicoe/seqdb-ui:0.1.dev
    environment:
      API_ADDRESS: seqdb-api:8080
    volumes:
      # Override the proxy config to auto-authenticate as Admin for demo purposes:
      - "./config/seqdb-demo.Caddyfile:/etc/Caddyfile"
    ports:
      - "2016:8080"
