-- How to use it: awk 'FNR==NR{A[$1]=$2;next}{for(i in A)sub("\"i,A[i], $0)}1' env.env setup_schema_user_permission.sql
-- env.env file format should be like $DB_NAME seqdb_test
-- Create Schema and Revoke privileges for PUBLIC user
REVOKE CONNECT ON DATABASE $DB_NAME FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS $SCHEMA_NAME;
REVOKE CREATE ON SCHEMA $SCHEMA_NAME FROM PUBLIC;

-- migration user
CREATE ROLE migration_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD '$MIGRATION_USER_PW';
GRANT CONNECT ON DATABASE $DB_NAME TO migration_user;
GRANT USAGE, CREATE ON SCHEMA $SCHEMA_NAME TO migration_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA $SCHEMA_NAME GRANT ALL PRIVILEGES ON TABLES TO migration_user;

-- web user
CREATE ROLE web_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD '$WEB_USER_PW';
GRANT CONNECT ON DATABASE $DB_NAME TO web_user;
GRANT USAGE ON SCHEMA $SCHEMA_NAME TO web_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA $SCHEMA_NAME TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA $SCHEMA_NAME GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA $SCHEMA_NAME GRANT SELECT, USAGE ON SEQUENCES TO web_user;
